name: travlr-id-prod

x-keria-common: &keria-common
  restart: unless-stopped
  image: ${KERIA_IMAGE:-weboftrust/keria:latest}
  environment:
    - KERI_AGENT_CORS=true
    - ALLOW_INTRODUCTIONS=true
    - REMOTE_SIGNING=true
  volumes:
    - travlr-keria-data:/usr/local/var/keri
  entrypoint: keria start --config-dir ./scripts --loglevel INFO
  logging:
    driver: "json-file"
    options:
      max-size: "1024k"
      max-file: "200"

x-witness-common: &witness-common
  restart: unless-stopped
  image: ${WITNESS_IMAGE:-weboftrust/keri:1.1.26}
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONIOENCODING=UTF-8
    - INITIAL_HTTP_PORT=5642
    - INITIAL_TCP_PORT=5632
    - KERI_VAR_DIR=/usr/local/var/keri
    - KERI_SCRIPT_DIR=/usr/local/var/keri/scripts
    - LOG_LEVEL=INFO
  entrypoint: ["bash", "-c", "export WITNESS_NO=$$(hostname | awk -F- '{print $$NF}'); exec kli witness start --loglevel $${LOG_LEVEL} --name travlr-wit$${WITNESS_NO} --alias travlr-wit$${WITNESS_NO} -H $$(( INITIAL_HTTP_PORT + WITNESS_NO ))"]
  volumes:
    - travlr-witnesses-config:/usr/local/var/keri
  logging:
    driver: "json-file"
    options:
      max-size: "1024k"
      max-file: "200"

services:
  # KERIA Agent for Travlr-ID - RESTORE ORIGINAL WORKING CONFIG
  keria-local:
    profiles: [keria-local,local,dev]
    <<: *keria-common
    ports:
      - 3904:3901  # Admin API
      - 3905:3902  # Agent API  
      - 3906:3903  # Boot API
    environment:
      - KERI_AGENT_CORS=true
      - KERI_AGENT_CORS_ORIGINS=http://localhost:3000,http://localhost:8100,http://localhost:5173,http://localhost:3001,http://0.0.0.0:3000
      - ALLOW_INTRODUCTIONS=true
      - REMOTE_SIGNING=true

  # Travlr Credential Server - hosts schemas and creates ACDC credentials
  travlr-credential-server:
    profiles: [credential-server,local,dev]
    build:
      context: ./travlr-ionic-app/credential-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3008:3001"  # Schema OOBI endpoint and API  
    environment:
      - OOBI_ENDPOINT=http://travlr-credential-server:3001
      - KERIA_ENDPOINT=http://keria-local:3901
      - KERIA_BOOT_ENDPOINT=http://keria-local:3903
      - PORT=3001
    depends_on:
      - keria-local
    volumes:
      - credential-server-data:/app/data

  keria-prod:
    profiles: [keria,production]
    <<: *keria-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travlr-keria.rule=Host(`keria.travlr-id.com`)"
      - "traefik.http.routers.travlr-keria.entrypoints=websecure"
      - "traefik.http.routers.travlr-keria.tls.certresolver=myresolver"
      - "traefik.http.services.travlr-keria.loadbalancer.server.port=3901"

  # Self-Hosted Public Witnesses for Travlr-ID
  travlr-witness-1:
    hostname: travlr-witness-1
    <<: *witness-common
    ports:
      - "5642:5642"  # HTTP
      - "5652:5632"  # TCP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness1.rule=Host(`witness1.travlr-id.com`)"
      - "traefik.http.routers.witness1.entrypoints=websecure"
      - "traefik.http.routers.witness1.tls.certresolver=myresolver"
      - "traefik.http.services.witness1.loadbalancer.server.port=5642"

  travlr-witness-2:
    hostname: travlr-witness-2
    <<: *witness-common
    ports:
      - "5643:5643"
      - "5653:5633"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness2.rule=Host(`witness2.travlr-id.com`)"
      - "traefik.http.routers.witness2.entrypoints=websecure"
      - "traefik.http.routers.witness2.tls.certresolver=myresolver"
      - "traefik.http.services.witness2.loadbalancer.server.port=5643"

  travlr-witness-3:
    hostname: travlr-witness-3
    <<: *witness-common
    ports:
      - "5644:5644"
      - "5654:5634"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness3.rule=Host(`witness3.travlr-id.com`)"
      - "traefik.http.routers.witness3.entrypoints=websecure"
      - "traefik.http.routers.witness3.tls.certresolver=myresolver"
      - "traefik.http.services.witness3.loadbalancer.server.port=5644"

  travlr-witness-4:
    hostname: travlr-witness-4
    <<: *witness-common
    ports:
      - "5635:5645"
      - "5625:5635"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness4.rule=Host(`witness4.travlr-id.com`)"
      - "traefik.http.routers.witness4.entrypoints=websecure"
      - "traefik.http.routers.witness4.tls.certresolver=myresolver"
      - "traefik.http.services.witness4.loadbalancer.server.port=5645"

  travlr-witness-5:
    hostname: travlr-witness-5
    <<: *witness-common
    ports:
      - "5636:5646"
      - "5626:5636"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness5.rule=Host(`witness5.travlr-id.com`)"
      - "traefik.http.routers.witness5.entrypoints=websecure"
      - "traefik.http.routers.witness5.tls.certresolver=myresolver"
      - "traefik.http.services.witness5.loadbalancer.server.port=5646"

  travlr-witness-6:
    hostname: travlr-witness-6
    <<: *witness-common
    ports:
      - "5637:5647"
      - "5627:5637"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness6.rule=Host(`witness6.travlr-id.com`)"
      - "traefik.http.routers.witness6.entrypoints=websecure"
      - "traefik.http.routers.witness6.tls.certresolver=myresolver"
      - "traefik.http.services.witness6.loadbalancer.server.port=5647"

  travlr-witness-7:
    hostname: travlr-witness-7
    <<: *witness-common
    ports:
      - "5638:5648"
      - "5628:5638"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness7.rule=Host(`witness7.travlr-id.com`)"
      - "traefik.http.routers.witness7.entrypoints=websecure"
      - "traefik.http.routers.witness7.tls.certresolver=myresolver"
      - "traefik.http.services.witness7.loadbalancer.server.port=5648"

volumes:
  travlr-keria-data:
  travlr-keria-config:
  travlr-witnesses-config:
  credential-server-data:
