version: "3.9"
services:
  keria:
    container_name: travlr-keria
    restart: unless-stopped
    image: cardanofoundation/cf-idw-keria:1.1.0-PR1223-25dbe26-GHRUN15555427316
    environment:
      - KERI_AGENT_CORS=true
      - ALLOW_INTRODUCTIONS=true
      - REMOTE_SIGNING=true
    volumes:
      - keria-data:/usr/local/var/keri
      - ./keria-config/config.json:/keria/scripts/keri/cf/backer-oobis.json
    entrypoint: keria start --config-file backer-oobis --config-dir ./scripts --loglevel INFO
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903

volumes:
  keria-data:
