version: '3.8'

services:
  witness:
    image: ${WITNESS_IMAGE:-weboftrust/keri:1.1.26}
    container_name: travlr-witness-${WITNESS_NUMBER:-1}
    hostname: travlr-witness-${WITNESS_NUMBER:-1}
    ports:
      - "${WITNESS_PORT:-5631}:5642"
      - "${WITNESS_TCP_PORT:-5621}:5632"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - WITNESS_NUMBER=${WITNESS_NUMBER:-1}
      - KERI_VAR_DIR=/usr/local/var/keri
      - KERI_SCRIPT_DIR=/usr/local/var/keri/scripts
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-travlrid.com}
    entrypoint: ["bash", "-c", "exec kli witness start --loglevel $${LOG_LEVEL} --name travlr-wit$${WITNESS_NUMBER} --alias travlr-wit$${WITNESS_NUMBER} -H 5642 -T 5632"]
    volumes:
      - witness-data:/usr/local/var/keri
      - ./witness-config:/usr/local/var/keri/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5642/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  witness-data:
    driver: local
